<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <Version>2.1.0</Version>
    <AssemblyVersion>2.1.0.0</AssemblyVersion>
    <FileVersion>2.1.0.0</FileVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>Resources\StayActive.ico</ApplicationIcon>
    <PublishReadyToRun>true</PublishReadyToRun>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\StayActive.Core\StayActive.Core.csproj" />
    <Resource Include="Resources\StayActive.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio.Wasapi" Version="2.2.1" />
    <FrameworkReference Include="Microsoft.Windows.SDK.NET.Ref" />
  </ItemGroup>

</Project>
